name: Deploy to Arsys (SFTP)

on:
  push:
    branches: [ "main" ]
    workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: "."
          remote_path: "/html/fichajes"
          delete: false
          exclude: >
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/*.log
            **/.env
